# Generated by Django 6.0.4 on 2026-05-09 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('outletmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
